import { useCallback } from 'react';
import jsPDF from 'jspdf';
import toast from 'react-hot-toast';

export const usePDF = () => {
  const exportTripPDF = useCallback(async (trip) => {
    const toastId = toast.loading('Generating PDF...');
    try {
      const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
      const pageW = doc.internal.pageSize.getWidth();
      const margin = 20;
      const contentW = pageW - margin * 2;
      let y = 20;

      const addPage = () => { doc.addPage(); y = 20; };
      const checkY = (needed = 20) => { if (y + needed > 270) addPage(); };

      // Header
      doc.setFillColor(79, 70, 229);
      doc.rect(0, 0, pageW, 45, 'F');
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(22);
      doc.setFont('helvetica', 'bold');
      doc.text(trip.title || `${trip.city} Trip`, margin, 22);
      doc.setFontSize(11);
      doc.setFont('helvetica', 'normal');
      doc.text(`${trip.city}, ${trip.country} • ${trip.duration} Days • ${trip.travelers} Traveler(s)`, margin, 34);
      y = 60;

      // Summary
      if (trip.generatedItinerary?.summary) {
        doc.setTextColor(30, 41, 59);
        doc.setFontSize(14);
        doc.setFont('helvetica', 'bold');
        doc.text('Trip Summary', margin, y); y += 8;
        doc.setFontSize(10);
        doc.setFont('helvetica', 'normal');
        const summaryLines = doc.splitTextToSize(trip.generatedItinerary.summary, contentW);
        doc.text(summaryLines, margin, y);
        y += summaryLines.length * 5 + 10;
      }

      // Daily Itinerary
      const days = trip.generatedItinerary?.dailyPlan || [];
      days.forEach((day) => {
        checkY(30);
        doc.setFillColor(240, 238, 255);
        doc.rect(margin, y - 5, contentW, 12, 'F');
        doc.setTextColor(79, 70, 229);
        doc.setFontSize(12);
        doc.setFont('helvetica', 'bold');
        doc.text(`Day ${day.day}: ${day.theme || ''}`, margin + 3, y + 3);
        y += 14;

        ['morning', 'afternoon', 'evening'].forEach((period) => {
          const activities = day[period] || [];
          if (!activities.length) return;
          checkY(15);
          doc.setTextColor(100, 116, 139);
          doc.setFontSize(9);
          doc.setFont('helvetica', 'bold');
          doc.text(period.toUpperCase(), margin + 3, y); y += 6;

          activities.forEach((act) => {
            checkY(20);
            doc.setTextColor(30, 41, 59);
            doc.setFontSize(10);
            doc.setFont('helvetica', 'bold');
            doc.text(`${act.time || ''} - ${act.title || ''}`, margin + 6, y); y += 5;
            if (act.description) {
              doc.setFont('helvetica', 'normal');
              doc.setFontSize(9);
              const lines = doc.splitTextToSize(act.description, contentW - 10);
              doc.text(lines, margin + 6, y);
              y += lines.length * 4 + 4;
            }
          });
        });
        y += 5;
      });

      // Budget
      const budget = trip.generatedItinerary?.budgetBreakdown;
      if (budget) {
        checkY(60);
        doc.setTextColor(79, 70, 229);
        doc.setFontSize(14);
        doc.setFont('helvetica', 'bold');
        doc.text('Budget Breakdown', margin, y); y += 8;
        Object.entries(budget).forEach(([key, val]) => {
          if (!val) return;
          checkY(8);
          doc.setTextColor(30, 41, 59);
          doc.setFontSize(10);
          doc.setFont('helvetica', 'normal');
          doc.text(`${key.charAt(0).toUpperCase() + key.slice(1)}: ${val}`, margin + 3, y);
          y += 6;
        });
      }

      // Travel Tips
      const tips = trip.generatedItinerary?.travelTips || [];
      if (tips.length) {
        checkY(30);
        y += 5;
        doc.setTextColor(79, 70, 229);
        doc.setFontSize(14);
        doc.setFont('helvetica', 'bold');
        doc.text('Travel Tips', margin, y); y += 8;
        tips.forEach((tip, i) => {
          checkY(10);
          doc.setTextColor(30, 41, 59);
          doc.setFontSize(10);
          doc.setFont('helvetica', 'normal');
          const lines = doc.splitTextToSize(`${i + 1}. ${tip}`, contentW - 6);
          doc.text(lines, margin + 3, y);
          y += lines.length * 5 + 2;
        });
      }

      // Footer
      const pageCount = doc.getNumberOfPages();
      for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(148, 163, 184);
        doc.text(`Generated by AI Trip Planner • Page ${i} of ${pageCount}`, pageW / 2, 290, { align: 'center' });
      }

      doc.save(`${trip.city}-itinerary.pdf`);
      toast.success('PDF downloaded!', { id: toastId });
    } catch (err) {
      toast.error('PDF export failed', { id: toastId });
      console.error(err);
    }
  }, []);

  return { exportTripPDF };
};
